function searchFunction() {
    let input = document.getElementById('searchInput').value.toLowerCase();
    let data = [
        '<a href="..\Pages\Subpages\Gamellection Subpages\3Slices.html">3 Slices</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\3Slices2.html">3 Slices 2</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\2048.html">2048</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\AchievementUnlocked.html">Achievement Unlocked</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\Antbuster.html">Antbuster</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\AwesomePlanes.html">Awesome Planes</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\AwesomeTanks.html">Awesome Tanks</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\AwesomeTanks2.html">Awesome Tanks</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BigFLAPPYTowerVSTinySquare.html">Big FLAPPY Tower VS Tiny Square</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BigICETowerTinySquare.html">Big ICE Tower Tiny Square</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BigNEONTowerVSTinySquare.html">Big NEON Tower VS Tiny Square</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BigTowerTinySquare.html">Big Tower Tiny Square</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BigTowerTinySquare2.html">Big Tower Tiny Square 2</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BTD.html">Bloons Tower Defense</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BTD2.html">Bloons Tower Defense 2</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\BTD3.html">Bloons Tower Defense 3</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\Connect4.html">Connect 4</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\CookieClicker.html">Cookie Clicker</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\EscapeRoad.html">Escape Road</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\FiveNightsAtWinstons.html">Five Nights at Winston&apos;s</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\GoogleSnake.html">Google Snake</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\HongKong97.html">Hong Kong 97</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\LearnToFly.html">Learn to Fly</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\LearnToFly2.html">Learn to Fly 2</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\LearnToFly3.html">Learn to Fly3</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\MinecraftClassic.html">Minecraft Classic</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\MooMoo.html">Moo Moo</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\n-gon.html">n-gon</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\NewSuperMarioBros.html">New Super Mario Bros.</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\Pac-Man.html">Pac-Man</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\QuickDrawWithGoogle.html">Quick, Draw!</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\Run3.html">Run 3</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\ShellShockers.html">Shell Shockers</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\Slope.html">Slope</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\SmashKarts.html">Smash Karts</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\Tetris.html">Tetris</a>',
        '<a href="..\Pages\Subpages\Gamellection Subpages\Wordle+.html">Wordle+</a>',
    ];
    let result = data.filter(item => item.toLowerCase().includes(input));
    document.getElementById('result').innerHTML = result.length ? result.join(", ") : "rest in piss";
}
